// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurationApp.Models;

namespace RestaurationApp.Migrations
{
    [DbContext(typeof(RestaurantContext))]
    [Migration("20190309184500_Added Person table")]
    partial class AddedPersontable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RestaurationApp.Models.Cuisine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CuisineDescription");

                    b.Property<string>("CuisineName");

                    b.Property<string>("ImgUrl");

                    b.HasKey("Id");

                    b.ToTable("Cuisines");
                });

            modelBuilder.Entity("RestaurationApp.Models.Dish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Cost");

                    b.Property<int?>("CuisineId");

                    b.Property<string>("Description");

                    b.Property<string>("DishName");

                    b.Property<int?>("TypeOfDishId");

                    b.HasKey("Id");

                    b.HasIndex("CuisineId");

                    b.HasIndex("TypeOfDishId");

                    b.ToTable("Dishes");
                });

            modelBuilder.Entity("RestaurationApp.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("FirstName");

                    b.Property<string>("ImgUrl");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("RestaurationApp.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName");

                    b.Property<string>("MailAddress");

                    b.Property<int>("NumberOfGuests");

                    b.Property<DateTime>("ReservationDate");

                    b.Property<string>("SecondName");

                    b.Property<string>("TelephoneNumber");

                    b.HasKey("Id");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("RestaurationApp.Models.RestaurantTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NumberOfChairs");

                    b.Property<int?>("ReservationId");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.ToTable("RestaurantTables");
                });

            modelBuilder.Entity("RestaurationApp.Models.TypeOfDish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("TypesOfDishes");
                });

            modelBuilder.Entity("RestaurationApp.Models.Dish", b =>
                {
                    b.HasOne("RestaurationApp.Models.Cuisine", "Cuisine")
                        .WithMany()
                        .HasForeignKey("CuisineId");

                    b.HasOne("RestaurationApp.Models.TypeOfDish", "TypeOfDish")
                        .WithMany()
                        .HasForeignKey("TypeOfDishId");
                });

            modelBuilder.Entity("RestaurationApp.Models.RestaurantTable", b =>
                {
                    b.HasOne("RestaurationApp.Models.Reservation")
                        .WithMany("Tables")
                        .HasForeignKey("ReservationId");
                });
#pragma warning restore 612, 618
        }
    }
}
